try:
    OIIOOIIOOIIIIOIIIOOOOIOIIIOOIIO=lambda MasterJayIsGoingToBeAGreatestPythonCoder:ZeroDivisionError;hasattr=True;import base64 as IOOIOOIOIOIOIIOIIOIOIOIIIOOOIOI
    BZBZBZBZBBBBBBBBBBZBZBZBBZBZBKOLSDMFGIEWHRIEWGRUEWRUDSFJBDSJGIEUGIFEWBKWFGWIFHWKFWKFGW=(lambda OIOOIOIIOIOIIOOIIOOIOOIOIOIIIOI, OIOOIIIOIIOOIOIIOOIOIOOIOOIOIOI, OIIIOIIOIOOIOIOIOOIOOIOIIOIOIOI, IIOOOOIOIIOOIOOOMOIIOOIOIOIIOOI, OIIIII=0: None)
    bignigga=[1],[2],[3],[4],[5],[6],[7],[8],[9],[10];smallnigga=[11],[12],[13],[14],[15],[16],[17],[18],[19],[20]; OIIOOIIOOIIIIOIIIOOOOIOIIIOOIIO()if bignigga==1 and smallnigga==11 else BZBZBZBZBBBBBBBBBBZBZBZBBZBZBKOLSDMFGIEWHRIEWGRUEWRUDSFJBDSJGIEUGIFEWBKWFGWIFHWKFWKFGW,None
    import random as OIOOIOIIOIOIIOOIIOOIOOIOIOIIIOI,math as OIOOIIIOIIOOIOIIOOIOIOOIOOIOIOI,time as IOIOIOOIIOOIOIIIOIOOIOOOIIOIIOO
    import sys as OIIIOIOOIOIOOOIOOOOIOIIOIIOIOIO,os as IIOIOIOOIOIIOIIOOOO,json as OIOIIOIIOOIIIOIOOIOOOIIOIOOIOOI
    class OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO:
        def _1_MRBEAST_():
            try:
                from OIIIOIIOIOOIOIOIOOIOOIOIIOIOIOI import IOIOIIIOOOIOOIIIOIOIIOOIOIOIIIIOO as OIIOIOIOIIIIIOOOIOIIIOOOOOIOIIIO
                IOIIIOIIOOIOIIOIIIIOOIIIIOOIOOIOO = None
                IOOIIOOIIOOIOOOOIIIOOIOIIIIIOOIOI = []
                OIOIIOOIOIIIOIIOOIOOIOOIIIIOOIOOO = {}
                IIIIIOOOOIOIOOIIIOIIOOOOIIIOOIOOO = 0
                def IOIIIIIOOIOIOOIOIIIIIOOOOIOOIOO():
                    pass
                def OIIOOIOOIOIOOIOOOIIIIOOIOOIIIOO(x, y, z=IOOIIOOIIOOIOOOOIIIOOIOIIIIIOOIOI):
                    pass
                def OIIIOOIOIIOOOIOOOIIIOIIOIOOOOOO(a=OIOIIOOIOIIIOIIOOIOOIOOIIIIOOIOOO):
                    return
                def OIIIIOOIIIOOIOOIOOIOOIOOIIIOIOI(*args, **kwargs):
                    pass
                def OOIOOIOIIOOIOIIIOOIOOOOOOOOIIII(param1=None, param2=None):
                    return
                def OIIOOIOIIOIIOOIIOOIOOIOOIOIOOIO():
                    pass
                def OIOIOIIOIOIIOIIOIOIOOIOIIIOIIOII(m=None):
                    return
                class OOOIIIIOIOIOOIOOIOOIIIIOOIIIOIO:
                    OIIIIOOIOOIOIIOIOIOIOOIOOIIIIIOO = None
                    IOOIIOOIIIOOIOOIIIOOIIOIIIOOIOO = 17
                    def __init__(self):
                        self.IOOIOIIOOIOOIOOIIIIOIIOOIOIOO = []
                        self.OOIIIIOOOIOIOIOOIIIIOOIOOOTIOO = {}
                    def OOOOIOOOIOOIOOIOIIOIOOOIOIOIOOO(self, XOXIX):
                        return None
                class IOIIOOOOOOOOIOIIIOIOOIOOOIIOOOO:
                    def __new__(cls):
                        return super().__new__(cls)
                    def IOIIIOIIIOOIOOOIIIOOIOIOOIOIOO(self, IIIN):
                        return
                OIOIIOIIOIIOIIIOIIOIOOIOIOIIOOIOO = [IOIIIOIIOOIOIIOIIIIOOIIIIOOIOOIOO for _ in range(10)]
                IOOIOIIIOOIIIIOIIIOOIIIIOOIOOOIOO = (IOOIIOOIIOOIOOOOIIIOOIOIIIIIOOIOI for _ in range(5))
                OOIIOIIIOOIOIIIOOIIIOOOOIOIIOOII = (lambda OIOIIIOIIIIOOOOOIOIIIIOOIOOIII: None)
                OOIIIOOIOIIOIOIIIIOOIOOIIIOOIIOII = IOIIIOIIOOIOIIOIIIIOOIIIIOOIOOIOO
                OIIIIIOOOOOOIOOIOOOOIOOOIOIIIIII = lambda OIOOIOOIOIIIIOOIOIOOIOIOOOOIO: OIOIIOOIOIIIOIIOOIOOIOOIIIIOOIOOO
                for IOOOIIIIIIIOOIIOOIOOOOIIIIIOIO in range(5):
                    IOIIIIIOOIOIOOIOIIIIIOOOOIOOIOO()
                    if IOOOIIIIIIIOOIIOOIOOOOIIIIIOIO % 2 == 0:
                        OOIIIOOIOIIOIOIIIIOOIOOIIIOOIIOII = IOOOIIIIIIIOOIIOOIOOOOIIIIIOIO
                def IOOIOIOOIOOIIIOOOIIOOIOOIIIOOOI(
                    a=IOIIIOIIOOIOIIOIIIIOOIIIIOOIOOIOO,
                    b=IIIIIOOOOIOIOOIIIOIIOOOOIIIOOIOOO,
                    c=IOOIIOOIIOOIOOOOIIIOOIOIIIIIOOIOI,
                    d=OIOIIOOIOIIIOIIOOIOOIOOIIIIOOIOOO
                ):
                    return
                OIIIOOIIIIOOIOIOOOOIIIOOIIOOIOOII = [OOIIOIIIOOIOIIIOOIIIOOOOIOIIOOII for __ in range(3)]
                for IOLIOIOOIOOIIOIOOIIOIOIOOOIOOIO in OIIIOOIIIIOOIOIOOOOIIIOOIIOOIOOII:
                    pass
                def OIIOIOOOOIOOIOIOOOIIOOOOIOIOOIO(o, u, p, i):
                    return
                OIIOOIOOIOOOOOIIIOIOOIOOOOIIOIOO = {}
                try:
                    IOOIOIOOIOOIIIOOOIIOOIOOIIIOOOI()
                except:
                    pass
                def OIIOIIOIOOIIOIIIIOOIOOOOOOOIOOI(u, p, o, i):
                    pass
                for OIIIIOOIOOIOOIOIOOOOIOOOOIOOIOO in range(7):
                    OIOIIOIIOIIOIIIOIIOIOOIOIOIIOOIOO.append(None)
                def IOOIOOIOIIOOIOOIOOIOOIIIOOOOIOO(o='O', i='I'):
                    pass
                OOOIOIOOIOIIOOOOIOIOOOIIIIOIIIOO = (lambda OIOOOIIOIIIIIIIIOOIOOOIIIIOOOO: None)
                OIIOIIIOOOOIOIIOOIOOIOOIIIOOIOOI = None
                OIOIIOIIOIIOIOOOOIOIOIIOOIOIIOOII = [[] for _ in range(4)]
                def IOIOIIIOOOIOOIIIOIOIIIOOIIOOOOI():
                    class IOIIOOIOJOIOOOIOOIOOOOIIIOOIOOI:
                        pass
                    return None
                def IOOIOIIIIOOIOOOOIOOIIIOOOOIOOOI():
                    return
                def OIIIIIOIOIOOIOOIOOIOIOIIOOIOIOO(u, p, o=None, i=None):
                    return u
                IOOIOOIOOOOIOIIIOOOOOOIIIIOOOOII = None
                class OIIOIIIIIOOOOIIIOOIOOIIIOOIOIOO:
                    pass
                OIIOIOOIOOOOIOOOIOOOOIOOOIIOOIOO = []
                for u in OIOIIOIIOIIOIIIOIIOIOOIOIOIIOOIOO:
                    OIIOIOOIOOOOIOOOIOOOOIOOOIIOOIOO.append(IOIIIOIIOOIOIIOIIIIOOIIIIOOIOOIOO)
                OIOOIOIIOOOOIIOOIOIOOIOOIIIOOIOI = None
                def OOOIOIIIOOIOOOOOIOIOIIOOIOOIIIO():
                    return
                OIOOOIIIIOIOOOOIOOIIIOIOOOOIOOIO = []
                for IOIIOOOIIIOOOIIIOIOIIIOIOOIIIIO in range(6):
                    OIOOOIIIIOIOOOOIOOIIIOIOOOOIOOIO.append(None)
                OIIIIOOIIIOOIOIIOOIOOOOOOIOOIOOII = lambda: lambda: IOIIIOIIOOIOIIOIIIIOOIIIIOOIOOIOO
                OIOIIOIIOOIOIOOOIOOOOIIOOOOOOIOOO = OIIIIIOIOIOOIOOIOOIOIOIIOOIOIOO
                OOOIOIIOOIIIIOIOOOOIOOIIIOOIOOOOO = OIIOIIIIIOOOOIIIOOIOOIIIOOIOIOO
                OIIOIIIOOIOOIOIOIIIOOIOOIOOIOOIO = OOOIOIIOOIIIIOIOOOOIOOIIIOOIOOOOO
                def OIIOOOOIOOIOIIOOOOOIIIOOIIIOOOI():
                    def IOIIOOOOIIIIOIOIIIOOIOIOIIOOOI():
                        return
                    return
                OIIIOIOIIIIIOOOOIIOOIOOIOOIOOOOO = [u for u in OIOIIOIIOIIOIIIOIIOIOOIOIOIIOOIOO if u == None]
                def OOOIOOOIIDEOOOIOOIOOIOOOIOOIOOIO():
                    pass
                OIIOOIOIIOOIOOOOIOOIOOIOOIIIOOIOO = [OOIIOIIIOOIOIIIOOIIIOOOOIOIIOOII for _ in range(2)]
                for _ in OIIOOIOIIOOIOOOOIOOIOOIOOIIIOOIOO:
                    pass
                def IOOIIIOIOOIIOIOOIOOIIIOOIOIOOIIO(u, i, p, o):
                    pass
                OOIIIIOOIOIIIIIOOOIIIOOOIOOIOOOOI = range(3, 9)
                for p in OOIIIIOOIOIIIIIOOOIIIOOOIOOIOOOOI:
                    pass
                OIIIOIOOOOIOOIOIOIOOIOOOOIOOIOOII = {}
                def IOIOIOOIIOOIOOOOIOOOOIIIOIIIOOI(u='U', i='I', o='O', p='P'):
                    return
                OIIOOIOOIOIIOOIOIIIOIOOIOOIOOIIII = []
                for i in range(5):
                    OIIOOIOOIOIIOOIOIIIOIOOIOOIOOIIII.append(None)
                class IOOIIIOOIIIOIOOIOIIOIOOIOIOIIOOIO:
                    def __init__(self):
                        self.OIOOOOIOIOOIOOOIOOIOOOIIOOIIIO = IIIIIOOOOIOIOOIIIOIIOOOOIIIOOIOOO
                        self.IOOIOOIOIOOIOIOIOOIIOOOOIIOOIO = IOIIIOIIOOIOIIOIIIIOOIIIIOOIOOIOO
                def IOOOOIOOIOOIIOOIOIOIOOOOIOIIOOO():
                    pass
                for __ in range(12): continue
                OIIOBUTIOOOOOOOIOOOOOOOOIOIIIOOO = None
                OIOOIOOIOIIOOIOIIIIOOIOOIOOOIIOO = IOIIIOIIOOIOIIOIIIIOOIIIIOOIOOIOO
                def IIO(OI, IO): pass
                def IO(II, IO): return None
                IIIOIIOOIOIIOIOOOOIOOIOIOIIIOOOOI = (OOIIOIIIOOIOIIIOOIIIOOOOIOIIOOII for OOIIOIIIOOIOIIIOOIIIOOOOIOIIOOII in range(2))
                def IOOOIIOOOIOIOOIOOIOOIOOIOIOIOIIO():
                    return
                class OOIIOIIOOIIIIOIIOIIOOOOIIOOIOOII:
                    IOOIOIIIOOIOIOOIOOIOOIOOOOIOIIOO = None
                def IIOIOOOOIOOIIIOOOOOOIOOIOOIOIII(OOI):
                    return OOI
                def IOOIOOOOIOIIOOIOOIOOOOIOOIIIOO():
                    OOOIIIIOIOIOOIOOIOOIIIIOOIIIOIO.OOOOIOOOIOOIOOIOIIOIOOOIOIOIOOO(0)
                def OIOOOOOIIOOIOIOOIIIIOOIOOIOOIOOI():
                    IOOIOIIIOOIIIIOIIIOOIIIIOOIOOOIOO.__next__()
                def IOOOOIOIIIOOIOOIOOOIIOOIIOIOOIOO():
                    OIOIIOIIOOIOIOOOIOOOOIIOOOOOOIOOO('X','Y','Z')
                def OOOIIOOIOOIIOIIOOIOIIOOIOIIIIIOO():
                    IOOIIIOOIIIOIOOIOIIOIOOIOIOIIOOIO.OIOOOOIOIOOIOOOIOOIOOOIIOOIIIO()
                def IOOOOIIIIOOIOIOOOOIIIOOIIIOOOIO():
                    OIOIIOIIOIIOIOOOOIOIOIIOOIOIIOOII.clear()
                IOOIOOOOIOIIOOIOOIOOOOIOOIIIOO()
                OIOOOOOIIOOIOIOOIIIIOOIOOIOOIOOI()
                IOOOOIOIIIOOIOOIOOOIIOOIIOIOOIOO()
                OOOIIOOIOOIIOIIOOIOIIOOIOIIIIIOO()
                IOOOOIIIIOOIOIOOOOIIIOOIIIOOOIO()
            except Exception:
                pass
        def _2_COCOMELON_():
            try:
                for IIOOIIOIOOOOIOIOOOIOOIIIOOIOIIIO in range(3):
                    OIIIOIOIOOIOOOIIOOOOOIOIOIOOIIII = [None for _ in range(7)]
                    OIIIOOIIOIIIIIOOIOIOOIOOOOIOOIOO = 0
                    IOIOOOOIOIIOOIOOIOIOOIOOIOOOIIOI = lambda OIOIOIIIOOOOIIIOIOIOIOOIOIIIIO: OIOIOIIIOOOOIIIOIOIOIOOIOIIIIO
                    for OIIIOOIOIOOIIOIOOOOOIIIOOOIOOI in OIIIOIOIOOIOOOIIOOOOOIOIOIOOIIII:
                        IOOIIOOIOIIIOIIOOOOIIIOOIOIOOOOI = IOIOOOOIOIIOOIOOIOIOOIOOIOOOIIOI(OIIIOOIOIOOIIOIOOOOOIIIOOOIOOI)
                        OIIOIIOOOOIOIIIOOOIIIIOOIOOOIIOO = [IIOOIIOIOOOOIOIOOOIOOIIIOOIOIIIO for _ in range(2)]
                        IOIOIOOIOIIOIIOOIOIIOIIOIOOIIOOI = []
                        OOOOOIIIOOIIOIOOIOIIIIOOIOOOIIOO = {}
                    try:
                        IOOOIOIOOIIOOOOIOIIOOOOIIOIOOII = None
                    except:
                        OIIIIOIOOIOOIIOOIOIOIOIIOOIIIIOO = None
                    for IOIOOIIOOOOIIOOIIOOIOIOOIOIIIIO in range(2):
                        IOIIIIOIOIIOOIOOIOOIIIIOOIIIOOIO = []
                        OOOOIIOIOOIIOOIOOIOOIIIOIOIOIIIO = 0
                        for OIIOOIIOOIOIIOOIIOOOOIOIIIOOI in IOIIIIOIOIIOOIOOIOOIIIIOOIIIOOIO:
                            pass
                    IOOIOIIOOIOIIIOOOIIOOIIIOIIIOIOO = (lambda OIOIOIIOOIOIOIOIIOOIOIOOIOIIOO: OIOIOIIOOIOIOIOIIOOIOIOOIOIIOO)
                    OOIIOOIOIOIIOIOOOIOOOOIIIOIIIIOI = OOOOIIOIOOIIOOIOOIOOIIIOIOIOIIIO
                OIOOIOIIOIOOIOIOIIIOOOIIIOOIOOIII = [None, None, None]
                IIOOOIIOIIOOIOOIOOIIOOIOOOIIOOOI = None
                for IOOIOIIIOOOOOIOIOOOOIOOIOOOIOOI in range(6):
                    IIOOIOOIOIIOIOOIOOOIOOIIIOOIOIIO = {}
                IOIIIOOOIOIIIOIIOOIIOOIIIOOOIOOI = []
                class OIOIIIIIOOIIIOOIIIIOOIIIOOIIIO:
                    IIOIOIOIIOOIOIIOIOOIOIOIIOIOIIOO = None
                    def __init__(self):
                        self.IOOIIIOOIOOIOIIOIOOOIOIIIOOIOOI = []
                        self.IIOOIOIIOOIOIOOIOOIOIIOOIOIIOO = 0
                    def IOOIOOIOIIIOOIOOOOIOOIOIIOOOIIO(self, OIIOOIOOIOIOOIIIOIOIIOOIOOIOOII):
                        return None
                    def IOOOIIOIIOIOOIOOIOIIOIOOIOOIOIO(self, IOIIOIOOOOIOIOOIIIIOOIOOIOIOOIO):
                        return
                def OIIIOIIIIIOOIOOIOOIOOIIIOIIIIOO(IOOIOOOIIIOOIOIIOIOIIOOOIIOOOIIIO, IOOIIOIOIIOOIIIOOIOOIOOOOIOIIIOI):
                    pass
                IOIIIOIIIIOOOIIOOIOIIOOOIIOOOOIOI = [OIIOIIOOOOIOIIIOOOIIIIOOIOOOIIOO for __ in range(4)]
                OIOOIOOIIIOIIIOOOOOIOOIOOIIIIOIOO = lambda: IOOIOIIIOOOOOIOIOOOOIOOIOOOIOOI
                for IIOOIOOIOIIOOIIOOOOOIIIIIOOIOOI in IOIIIOIIIIOOOIIOOIOIIOOOIIOOOOIOI:
                    OIOOIOOIOOIOOOIOIOIIOIOOIIOIOOII = []
                for OIOOOIIOIOIOOOIIIOOIOOOOOIOIIIO in range(7):
                    IOIOIOOIOOIIIIOOOOIOOIOOIOOIOIOO = None
                OIIOOOIIIOOIOOIOIIOOIIIIOIIOOOOI = IOIIIOOOIOIIIOIIOOIIOOIIIOOOIOOI
                while False:
                    OOIOIIOIIOOIIIOOOOOIIOOOIIOOOOI = 0
                    break
                OOIOOIIIOOOIOIOOOOIOIIOOIOIOOIII = None
                def IOOOIIIIOIOOIOIOOOIIIOOIOIOIIOO(IOIOIOOIOIIOIIOOIOIIOIIOIOOIIOOI, OOOOIIOIOOIIOOIOOIOOIIIOIOIOIIIO):
                    return
                for IOOIIIIIOOIOIIIIIOOIIIIOIIOOIOOI in range(5):
                    try:
                        OIIOOIIOOIOIIOOIIOOOOIOIIIOOI = IOOIOIIOOIOIIIOOOIIOOIIIOIIIOIOO
                    except:
                        pass
                OIIIIOIIIIOOOIOOIOOIOOIOOOIIIOOI = [None for _ in range(8)]
                IIOOIIOIIOOIOOIOIIOOOIOIIIOOOIOO = {}
                class IOIOOIIIIIOIIOOOIOOIOOIIIIOIOII:
                    IOOIOIIIIIOOIOOIIIOOIOIOOIIOOIOO = []
                    def __init__(self):
                        self.IOOIIIIOOIOOIOOIOIIOOIOOIIIIOIO = IOOIOIIOOIOIIIOOOIIOOIIIOIIIOIOO
                        self.OIOIIOOIIIOIOIOIIIOOOIIOOIOOOOI = -1
                    def IOOIIIOOOIOIIIOOOOIOIOOIOIOIIOO(self, IOOOOOOOOIOOIOOIOOIIOOOIOOIIOIO):
                        return True
                def OIIOOIIOOOIIIOOIOOIOIIIOIOIIIOOIO(OIIOOIIOOIOIIOOIIOOOOIOIIIOOI=None):
                    return
                class IOOIIIOOIIIIIOIOOOOIOOIIOOIOOIOO:
                    def __init__(self):
                        self.IOOIOIIOOOOOIIIOOIOIIOOIOIOOIOO = IOIOOOOOOIOOIIOOIIIOOIOIOOOOIOOO
                    def OIIOIOOIOOIIOOIOOIIOOIIIIOIOIOO(self):
                        return
                def IOIOOOOOOIOOIIOOIIIOOIOIOOOOIOOO(OIIOOOIIOIOOIOOOOIIIOOIIIIOOIOOI='O', IOOOOIIOIOOIIOOOOIOOIOOIOOOOIOI='I'):
                    return
                OIOOIIIOOIOOIIIOOIIOOOIIOOOIIIOO = [OIIIIOIIIIOOOIOOIOOIOOIOOOIIIOOI for _ in range(3)]
                for __ in OIOOIIIOOIOOIIIOOIIOOOIIOOOIIIOO:
                    pass
                OIIIOIIOOIOIIIIOOOOOOOIIOOOOIOOI = None
                for OIIIIIOOIOIOIIOOIIOOOOIOOIIOOIO in range(9):
                    OIIOOOIIIOOIOOIOIIOOIIIIOIIOOOOI = []
                    IOOIIIIOIIOOIIIOOIOOIOIIIIOOOIOO = None
                    break
                IOIOIIIIOOOOIOOOOIIOOIIIOOOIOOIO = []
                OOOIOOIIIIIOOIOOOOIOOIOOIIIOIIOI = lambda: None
                OIIOOIOOIOOOIIOOIOOIOOIIIOOOIIOO = IOIOOOOIOIIOOIOOIOIOOIOOIOOOIIOI
                OIIOIIIOOOOIOOIOOIOOIIOOOIIIIOOO = {}
                IIOOOOOIIIIOOIOIOIIOOIIOOIIIIOOO = [OOIOOIIIOOOIOIOOOOIOIIOOIOIOOIII for _ in range(2)]
                for OOOIIOOIOOIOOIOOOOOIOIIOOIIOOO in IIOOOOOIIIIOOIOIOIIOOIIOOIIIIOOO:
                    IOOIIOOIOIIIOOIOOIIOOIOOIIIOOIOI = None
                from OIIIOIIOIOOIOIOIOOIOOIOIIOIOIOI import IIOIOIOOIOIIIOIOOIOIIOIIIOOOOIO as IOOIIOIIIOIOOIOIOIIOOIOIOOIIIOI
                def IOIOIIOOIOOOIOOIIIIIOIIOIOIOIOO():
                    pass
                def OIIOIOOIOIIIOIOIOOIOIOOIOIOOIOI():
                    pass
                def IIIIOIOOIIIOOIIIOIOOIIIOOIIIOOO():
                    pass
                def OOOIOOIIIOOOOIOOIIIIOOIIIOIIOIO():
                    pass
                def IOIIOOOIOOOIOOIOOIOOIOIIOOIIIOO():
                    pass
            except Exception:
                pass
        def _3_KIDSDIANA_SHOW_():
            UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU = None
            IIIIIIIIIIIIIIIIIIIIIIIIIIIIII = []
            OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO = {}
            PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP = 0
            def UIOPIUIUIUIOPOPIUIPIOIOUPIUIUIU():
                pass
            def POIUIOUPUUOPIUIUIOUPIOUIUIPUIIO(u, p):
                return None
            def OUIOPPPUIOPUIOUPOIUOIOIUUOPPIP(ppp, ioi=UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU):
                pass
            class UIPPOOPOIOPUIPUOPPUUPUIUIUPPPIO:
                UUIUOPPIOOUUIIPOIOPUIUIUPUIOIO = None
                PPPUIPOIUOUPPUIIOPUUIOPPUPPIUU = 42
                def __init__(self):
                    self.OOUUIPUOIUPUIIOPUIUOPIOPUI = []
                    self.PUUIPOIUUPUIUUIPIOIPUOPUPI = {}
                def POIUUPUIOUIPUOPUUOPIUOIUPOIPPO(SELF, UPUP):
                    return None
            class IOIUIOIUPOIUIPIOIPOUIPIOUIOIPUO:
                def __new__(CLS):
                    return super().__new__(CLS)
                def IOPIOUPPOIUOUPIUIPUIPUOPUUIUI(OPPPP):
                    return
            UIPOIPUIUOPIUIPUOIPUIPUUIUPOUIPO = [UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU for _ in range(10)]
            OIPUIPIUOUPUIPUIPOIUPOUIUIPOUIOI = (IIIIIIIIIIIIIIIIIIIIIIIIIIIIII for _ in range(5))
            PUIOUPPIOUPUIPOPUIPIOUPIUPIOUPPI = (lambda UUUUUIUIUIUIUIUIUIUIUIUIUU: None)
            POIUOUPIOIOPIUIPUOIPUIPOIPUUUOP = UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
            IOPPPUUIOPIUPOIPUIPUUIPIOIOPUPI = lambda PPPUUPOIUOPUIUOUIUOPPUUII: OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
            for OOIUIUIPUPIOOUOIPOUIUIIUPPIU in range(5):
                UIOPIUIUIUIOPOPIUIPIOIOUPIUIUIU()
                if OOIUIUIPUPIOOUOIPOUIUIIUPPIU % 2 == 0:
                    POIUOUPIOIOPIUIPUOIPUIPOIPUUUOP = OOIUIUIPUPIOOUOIPOUIUIIUPPIU
            def PUIOUIOPUIPUPUPUIOPUIPUPIUOUIUI(u=UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU,
                                                p=PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP,
                                                i=IIIIIIIIIIIIIIIIIIIIIIIIIIIIII,
                                                o=OOOOOOOOOOOOOOOOOOOOOOOOOOOOOO):
                return None
            PUIOPUIPOUIIOUPIOUOPUIUIOPUPUPO = [PUIOUPPIOUPUIPOPUIPIOUPIUPIOUPPI for _ in range(3)]
            for IIUOOUPPUIPPUOIOIPUIOIUUIPIPU in PUIOPUIPOUIIOUPIOUOPUIUIOPUPUPO:
                pass
            def IUPIOOIPUIOPUIPUUIPOUPUIOIPIOPO(o, u, p, i):
                return None
            PIOIUOPIOUPIOPUPUPUIOUPIOUPOIPP = {}
            try:
                PUIOUIOPUIPUPUPUIOPUIPUPIUOUIUI()
            except:
                pass
            def OOOPPUUIUUPPUIPUIUIPIUOUUPOOPP(u, p, o, i):
                pass
            for POIPUIPUIPOIUIPIUIOOPUUIIOIOUU in range(7):
                UIPOIPUIUOPIUIPUOIPUIPUUIUPOUIPO.append(None)
            def PIUOUPIPIOPUIPUOIUOIPUIPPIUUPP(o='O', i='I'):
                pass
            UPUIPOIUPUOPUOPUIOUPIUOPUIPUIOI = (lambda IUIOPUIOPUPUPUPIUOPPUIUOIPIO, OPUIPIPUIOPIOPPIUUUIOPPUPPO: None)
            PPPPPPUIPUOPPUIUPUPIUPIUOPPPUPI = None
            IIIIIIIIIIIIIIIIIIIIIIIIIIIIIII = [[] for _ in range(4)]
            def UUPPIOUUIPOUOPUIPOUPPIUPIPUPI():
                class IHATEBLACK:
                    pass
                return None
            def PUIPUOOUIOPPUIIPOPUOPPIUUOIUPU():
                return
            def OUIPOPIUOIPUIPIOUIPIPUOPIUPIOO(u, p, o=None, i=None):
                return u
            PUUIPOUUPOIUOPUIOPUUUIPPUIOOIOIU = None
            class PUIUOUUIPOIUIOUPOUIPUUOIPUPUI:
                pass
            IOIUIPOUUIPOUPIUOPPIOOUPPIOIPUOI = []
            for u in UIPOIPUIUOPIUIPUOIPUIPUUIUPOUIPO:
                IOIUIPOUUIPOUPIUOPPIOOUPPIOIPUOI.append(UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU)
            OUPIPOPIUOIPUOUIIPOIUPOIPUOIUPUU = None
            def _PUUIOIPOPIUOPIUOPOPUUIIPOUIOI():
                return
            PIOUIPUOIPUPUUPUIUUOPPUOOIUOUUIP = []
            for IIOPUIPOIUPUIPOUIUUPUUIOIUUOP in range(6):
                PIOUIPUOIPUPUUPUIUUOPPUOOIUOUUIP.append(None)
            OIPOIUPOIPUUUOUIPUOIPOOUUIPUOUU = lambda: lambda: UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
            PUIOUUIOUPIOPUUPUIIUUPOUUUIIOPI = PUIPUOOUIOPPUIIPOPUOPPIUUOIUPU
            UUUUUIUIIOUUOPUOUIUPUIPIIUUOPO = UIPPOOPOIOPUIPUOPPUUPUIUIUPPPIO()
            PIOUPOUIOPUOIPUIPUIPOPUOUIUOIUP = UUUUUIUIIOUUOPUOUIUPUIPIIUUOPO
            def UUIOIOIPIUPUIPOPIUUOPUPUPPOIU():
                def PUIOPQIOPOUPOUIUPIOIPOUUOUIP():
                    return
                return
            IPOUUIOUPUIIPOPUUIIPPUPIUOPUUOI = [u for u in UIPOIPUIUOPIUIPUOIPUIPUUIUPOUIPO if u == None]
            def OUPIUIPOUPUIUIOPUIUPOUPOPUIUP():
                pass
            def IOPOUIPUIPUPUIOUPPIUOIUPIOOUP(u, i, p, o):
                pass
            UPOPUIPUOPUIPUOPUIPUUPUIUUOIPOI = range(3, 9)
            for po in UPOPUIPUOPUIPUOPUIPUUPUIUUOIPOI:
                pass
            IOPUOPUOUPIOOUPIUIPUIOPOPUUOPPO = {}
            def UUIOPUIUIOPIUPOIUPOUUPUPOIPPI(u='U', i='I', o='O', p='P'):
                return
            POPIUIPUOPUUUPPOUUIOPPIOOUIPUIP = [] 
            for i in range(5): 
                POPIUIPUOPUUUPPOUUIOPPIOOUIPUIP.append(None)
            class OIPIOPOIUIOIPIUIUPOIPOIOIOIPI:
                def __init__(self):
                    self.PUUOUPIUUIOOPPIOIUPIUIUOUP = PPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
                    self.UIUUOIOIOIUOPUPUOPPIOPIIOPU = UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
            def PU_PIOPUOIOUPIUUUOUPOPIUIPPUO():
                pass
            for __ in range(12): 
                continue
            UPUPOIUPOPIUIPUUUOUPIPOIPOUPUOIP = None
            IOPIOUIOIUPUUOUOUUUUIPOPPUOUIIPO = UUUUUUUUUUUUUUUUUUUUUUUUUUUUUU
            def P(I, U):
                pass
            def U(P, I): 
                return None
            POIPUIOPOIUOPIOUIPIUUOIPPUUOIPU = (PUIOUPPIOUPUIPOPUIPIOUPIUPIOUPPI for PUIOUPPIOUPUIPOPUIPIOUPIUPIOUPPI in range(2))
            def IPOIUOUPOUIPOUUIAPIUPOPIUPOU():
                return
            class UPOIPUUOUPOIUOIPUOIPUIUOUUPOI:
                UUUPUOPIOUUPIOUOIUPOUPIPUUPOIU = None
            def OUIOIPOIPOUPIUOPOUIPUOUPIUUPO(POI, UPO):
                return POI
        def _4_LIKE_NASTYA_():
            PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII = None
            OIPUIOUPUIPUIUUPIUUPUIPUPUIPIOPO = []
            UIPUPUPOUIOIOPUUIPUOIPOPUIOPUUP = {}
            OOUUPUOPUIUIPIOUOPUIUOPUUPIOIIU = 0
            def OUPUPPUUPOUPIOUPIOPUIPIIUIPUOO():
                pass
            def IOUPUPUIOPIOPUIPUPIUIPUIPUUIPO(u, p):
                return None
            def UIPUPIPUPOUIOUPUUIPOUPUIPUPOUP(ppp, ioi=PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII):
                pass
            class UIPUIPUIUPUIPUIPUIUPUIPUIPUIPUP:
                UIPUIPUPOUIPUIPUIPUPUIPUIPPUIOP = None
                UIPPUPUIOPUIPUPUIPUOPUIOPUIPUIP = 2048
                def __init__(self):
                    self.OUPUUPUIUPUPIUIOUPUIPUPOIUPO = []
                    self.POUIUPUIPUIOIUPUPIPIUPUIPUPUI = {}
                def UIPUPUIPUIPUPUIUPUIPUPUIPUPUIP(self, POUPU):
                    return None
            class UIPUPOUIPUIPUIOPUPUIPUIPUIPUIOI:
                def __new__(cls):
                    return super().__new__(cls)
                def UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU(self, OIPUO):
                    return
            UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU = [PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII for _ in range(10)]
            UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUO = (OIPUIOUPUIPUIUUPIUUPUIPUPUIPIOPO for _ in range(5))
            UIPUPUIPUIPUIPUIPUIPUIPUIPUPUPUIPU = (lambda UPUIPUPOUIPUIUPUIPUIOIPPU: None)
            OIPOUPUIPUIPUIPUIPUIPUIPUIPUIPUIPU = PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII
            PUUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUI = lambda PUIPUPUIOPUIPUPUIPOPUIOIUPP: UIPUPUPOUIOIOPUUIPUOIPOPUIOPUUP
            for OUPUPOUIPUIPUIPUIPOIUUUPUUPUPU in range(5):
                OUPUPPUUPOUPIOUPIOPUIPIIUIPUOO()
                if OUPUPOUIPUIPUIPUIPOIUUUPUUPUPU % 2 == 0:
                    OIPOUPUIPUIPUIPUIPUIPUIPUIPUIPUIPU = OUPUPOUIPUIPUIPUIPOIUUUPUUPUPU
            def UIPUIPUIPUIPUIPUIPUIPUPOUIPUIPU(u=PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII,
                                                p=OOUUPUOPUIUIPIOUOPUIUOPUUPIOIIU,
                                                i=OIPUIOUPUIPUIUUPIUUPUIPUPUIPIOPO,
                                                o=UIPUPUPOUIOIOPUUIPUOIPOPUIOPUUP):
                return None
            POUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIP = [UIPUPUIPUIPUIPUIPUIPUIPUIPUPUPUIPU for __ in range(3)]
            for UOIPOUPUIPUIPUPUIPUPUIPUIPUPUIUP in POUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIP:
                pass
            def PUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUI(o, u, p, i):
                return None
            PUIPOUPUIPUIPUIPUIPUIPUIPUIPUIPUIP = {}
            try:
                UIPUIPUIPUIPUIPUIPUIPUPOUIPUIPU()
            except:
                pass
            def POUPUIPUIPUIPUIPUIPUIPUIPUIPUIPU(u, p, o, i): pass
            for UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIP in range(7):
                UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU.append(None)
            def OUPUIPUIPUIPUIPUIPUIPUIPUIPUIPUI(o='O', i='I'): pass
            IPIUPUIPUIPUIPUIPUIPUIPUIPUIPUIPUI = (lambda IUPUIPUIPUIPUI: None)
            OUPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIP = None
            UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPIPI = [[] for _ in range(4)]
            def UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU():
                class UIPUIPUIPUIPUIPUIPUIPUIUU:
                    pass
                return None
            def POUPUIPUIPUIPUIPUIPUIPUIPUIPUIU():
                return
            def UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPO(u, p, o=None, i=None):
                return u
            PUUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU = None
            class PUUIPUIPUIPUIPUIPUIPUIPUIPUIPUI:
                pass
            PUUIPUIPUIPUIPUIPUIPUIPUIPUIPOIPO = []
            for u in UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU:
                PUUIPUIPUIPUIPUIPUIPUIPUIPUIPOIPO.append(PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII)
            OUPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIP = None
            def UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIU():
                return
            OUPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU = []
            for UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIO in range(6):
                OUPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU.append(None)
            UIOPUIPUIPUIPUIPUIPUIPUIPUIPUIPUI = lambda: lambda: PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII
            PUUIPUIPUIPUIPUIPUIPUPUIPUIPUIPUI = POUPUIPUIPUIPUIPUIPUIPUIPUIPUIU
            UIPUUIPUIPUIPUIPUIPUIPUIPUIPUIPUA = PUUIPUIPUIPUIPUIPUIPUPUIPUIPUIPUI
            PUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUI = UIPUUIPUIPUIPUIPUIPUIPUIPUIPUIPUA
            def UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIO():
                def UIPUIPUIPUIPUIPUIPUIPUIPO():
                    return
                return
            UIPUIPUIPUIPUIPUIPUIPUIPOIUPUIPU = [u for u in UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU if u == None]
            def UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUII():
                pass
            UIPUIPUIPOIUPUIPUIPUIPUIPUIPUIPUI = (lambda POI, UPO: None)
            def IUPUIPUIPUIPUIPUIPUIPUIPUIPUIPU(u, i, p, o):
                pass
            PUUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUP = range(3, 9)
            for p in PUUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUP:
                pass
            UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUPO = {}
            def IUIPUIPUIPUIPUIPUIPUIPUIPUIPUIP(u='U', i='I', o='O', p='P'):
                return
            UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUOI = []
            for i in range(5): UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUOI.append(None)
            class PUUIPUIPUIPUIPUIPUIPUIPUIPUIPUP:
                def __init__(self):
                    self.PUIPUIPUIPUIPUIPUIPUIPUIPPUP = OOUUPUOPUIUIPIOUOPUIUOPUUPIOIIU
                    self.IUIPUIPUIPUIPUIPUIPUIPUIUPUI = PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII
            def UIPUIPUIPUIPUIPUIPUIPUIPUIPUPUP():
                pass
            for __ in range(12): continue
            OUPUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUO = None
            PUUIPUIPUIPUIPUIPUIPUIPUIPUIPUIPOU = PUUIPUUPUUUPPIOPIOIOIPUIOPIOUPPII
            def P(U, I): pass
            def U(P, I): return None
            UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUOP = (UIPUPUIPUIPUPUIPUPUIPUPUIPUPUIPU for UIPUPUIPUIPUPUIPUPUIPUPUIPUPUIPU in range(2))
            def UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPUP():
                return
            class UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPU:
                UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPI = None
            def UIPUIPUIPUIPUIPUIPUIPUIPUIPUIPII(POI, UPO):
                return POI
        def _5_VLADANDNIKI_():
            from OIIIOIIOIOOIOIOIOOIOOIOIIOIOIOI import IOOIIOIIIOIOOIOIOIIOOIOIOOIIIOI as IIOIOOOOIOOIOIIOIIOIOOOIOIOIIIO
            IOOIIIOIIIOOOOOOIOOIOOOOIOOIOOII = None
            OIIOOIOOIOOIOIIOIIOOOOIOIOIIIIO = []
            OIOIOOIIIOOIIOIIIOIOOOOIOIIOIOO = {}
            OIOIOIOOOIOIIOOOOIOIOIOIIIOOIOO = 0
            def IOOIOOIOOIOOOOIOOOIOOOOIIIOOIO():
                pass
            def OOOOIOIIOIOIOOOIOOIOOOIIIIIOOOO(x, y, z=OIIOOIOOIOOIOIIOIIOOOOIOIOIIIIO):
                pass
            def OIIOIOOOOIOOOIIIIOOIOOIOOIOIIOO(a=OIOIOOIIIOOIIOIIIOIOOOOIOIIOIOO):
                return
            def IIOIOOIOIOOOOIOOIIIOIIIIIOIIOO(*args, **kwargs):
                pass
            def IOOOIOOIIIOOIOIIOOOOIOIOIOIOOOO(param1=None, param2=None):
                return
            def IOIIOIOOIOIOOIOOOOOOIIIOOIIIOO():
                pass
            def IOIOIOIIOOOIOIOOOOIIIOIIOIIIOI(m=None):
                return
            class IOIIOOIOOOOIOIOIIIOOIOIIOOOIIO:
                OIOOIOIIIOOOOIIIOOIOOOOIOIOIIOO = None
                IOOIOOIOOIIOOIOIIOOIOIOOOOIOOIO = 13
                def __init__(self):
                    self.IOIOIOIIIOOIOOIOIOOIOIOOIOOOO = []
                    self.OIIOOIOOIIOOIOOIIOOIIIOOIOIIO = {}
                def OIOIOOIIIOOOOIOOIOIOIIOOIIIII(self, POIOI):
                    return None
            class OOOOOIOIIIIOOIIIIOOIIOIOOOIOOOO:
                def __new__(cls):
                    return super().__new__(cls)
                def OOOIOIIOIOOIOOOOOIIOOOIIIOOIO(self, IOOIN):
                    return
            OIOOIOOIIIOIOIIIOIOOOOIIIOIIOIOO = [IOOIIIOIIIOOOOOOIOOIOOOOIOOIOOII for _ in range(10)]
            IOOIOOOIOOIOIIOIIIIOIIOIIIIOOIOO = (OIIOOIOOIOOIOIIOIIOOOOIOIOIIIIO for _ in range(5))
            OIOIOOOOIIIOOIOIOIIOIOOOIIOIOOII = (lambda IIIIOOOOOOOIIIIOIIOOIOOIOOOI: None)
            OIOOIIIOOOIIOOOOIIOOIOOIIIOOIOOI = IOOIIIOIIIOOOOOOIOOIOOOOIOOIOOII
            IIOIIIOOOOIOIOOIOOOOIIIIIOIIOIOO = lambda IOIOIOOIOOIIIIOOIOIOIOOIOOIOO: OIOIOOIIIOOIIOIIIOIOOOOIOIIOIOO
            for IIOOOIOIOOIOIOIIOOIOIOIIOOIOIO in range(5):
                IOOIOOIOOIOOOOIOOOIOOOOIIIOOIO()
                if IIOOOIOIOOIOIOIIOOIOIOIIOOIOIO % 2 == 0:
                    OIOOIIIOOOIIOOOOIIOOIOOIIIOOIOOI = IIOOOIOIOOIOIOIIOOIOIOIIOOIOIO
            def IOIOOOOIOOIOIIOOIOOIOOIOOIIIOO(
                a=IOOIIIOIIIOOOOOOIOOIOOOOIOOIOOII,
                b=OIOIOIOOOIOIIOOOOIOIOIOIIIOOIOO,
                c=OIIOOIOOIOOIOIIOIIOOOOIOIOIIIIO,
                d=OIOIOOIIIOOIIOIIIOIOOOOIOIIOIOO
            ):
                return
            OIOIOOIOIIIOOIIOOIIIOOIIIIOOIOII = [OIOIOOOOIIIOOIOIOIIOIOOOIIOIOOII for __ in range(3)]
            for IOOIOIOOOIIOOIOOIOOIIIOIIIOOIO in OIOIOOIOIIIOOIIOOIIIOOIIIIOOIOII:
                pass
            def IOOIOOIOIOIIIIOIIOIIIOOIIIIOOOO(o, u, p, i):
                return
            OIIIOOIOIIOIOIIIIOOOIOOOOIOOOOIO = {}
            try:
                IOIOOOOIOOIOIIOOIOOIOOIOOIIIOO()
            except:
                pass
            def OIIOIOOIIIOOIIIOOOIIIIOOOOIOOO(u, p, o, i):
                pass
            for IOIOIOOIOIIOIIOIOOIIOIOIOOIIOO in range(7):
                OIOOIOOIIIOIOIIIOIOOOOIIIOIIOIOO.append(None)
            def IOIOOIOOOIOOIOOIIIOOIIIOOOIOOO(o='O', i='I'):
                pass
            IIIIOIOOIOOOIIIOOOIOIOOIIIOOIOOO = (lambda IOIOOIOOIOOIOIOOIOOOO_IOIIIO: None)
            IOOIOIIIOOOIIOOOOOOOOOIIOOIOIIOO = None
            IOIOOIIOOIIIOOIOOIOOIIIOIIOIIIOO = [[] for _ in range(4)]
            def IOIIOOIOIOIOIOIIOIIIOOOOIIIOOI():
                class OIOOOIOOIIIOOIIOIOOOIOIOOIOIIO:
                    pass
                return None
            def OIOIIOOIIOOOOIOOIOIOIIIOOIOOIO():
                return
            def OIOIIOOIOIIOOOIIIIOIOIIOOOIIOO(u, p, o=None, i=None):
                return u
            IOIIOOIOOIOOIOIOOIIIIOOIIOOIIII = None
            class OIIOIIOOIOOOOIIIOOIOOIIIOIOIOI:
                pass
            IIOOIOOIOIOOIOOIOIOIOOIOOIOIIOOI = []
            for u in OIOOIOOIIIOIOIIIOIOOOOIIIOIIOIOO:
                IIOOIOOIOIOOIOOIOIOIOOIOOIOIIOOI.append(IOOIIIOIIIOOOOOOIOOIOOOOIOOIOOII)
            OIIIIOOIOOIOOIIIOIOOOIIOIIIOOIOI = None
            def IOIIIIOOIOOIIIIOIIIOIOIOOOIIOOI():
                IIOIOOOOIOOIOIIOIIOIOOOIOIOIIIO.OIOOIOOOIIOIIIOOIOOIIOIOIIOOIIO()
            def IOIIOOIIOOIOOOIIIOOIIOOIOOIOIIO():
                return
            IOIOOIIIIIOOIIOOOOIIOOIIIOOOOIOI = []
            for OOIOIOOOIIIOOIOOOOIOOIOIIOIIOO in range(6):
                IOIOOIIIIIOOIIOOOOIIOOIIIOOOOIOI.append(None)
            OIOOIOOIOOOIIIOOIOIIIOIIIOOIIIOI = lambda: lambda: IOOIIIOIIIOOOOOOIOOIOOOOIOOIOOII
            OIOIOOIOIIIOOIOIIOIIIOOOOIOOIIOO = OIOIIOOIIOOOOIOOIOIOIIIOOIOOIO
            OOOIOOIOOIIOOOOIOIIOOIOIOIIIOOIO = OIIOIIOOIOOOOIIIOOIOOIIIOIOIOI
            def OIOOIIIOIOOIIOOIOOOOIIIIOOOIIO():
                def IIOIOOOIIIOIOOIIIOOIOOIOIIIIO():
                    return
                return
            OOOIOIIOOOIIOIIIOOIIOOIOOIOIIOIO = [u for u in OIOOIOOIIIOIOIIIOIOOOOIIIOIIOIOO if u == None]
            def IOIOIOIOOIOOIOIOIOOOOIOOIIIIIO():
                pass
            OOIOOOOIOIOOOOIIIOOIOIOOOIOIIOIO = [OIOIOOOOIIIOOIOIOIIOIOOOIIOIOOII for _ in range(2)]
            for _ in OOIOOOOIOIOOOOIIIOOIOIOOOIOIIOIO:
                pass
            def IOIOOIIIOIOOOOIOOIOOIOOIORIOII(u, i, p, o):
                pass
            IOOIIIOOIOIOOOOOIOOIIIOOIOIOOIOI = range(3, 9)
            for p in IOOIIIOOIOIOOOOOIOOIIIOOIOIOOIOI:
                pass
            IOOOOOOIOIIOOIOOIOOIOOOOIOOIOIIO = {}
            def IOIIOIOOIOIOOOOIOIOOIIIOOOOIOI(u='U', i='I', o='O', p='P'):
                return
            OIOIIOOIOOOIOIOIIOOIIIIOOOOIOIII = []
            for i in range(5):
                OIOIIOOIOOOIOIOIIOOIIIIOOOOIOIII.append(None)
            class IOIOIIOOIOOOIOIOIIOOIOOIIIOOIIO:
                def __init__(self):
                    self.IOOIOOIIIOOIOOOOIOIIOIOOIOOIOO = OIOIOIOOOIOIIOOOOIOIOIOIIIOOIOO
                    self.OIIIOOIOOIOOIOIOOIOIIOOOIIIOOI = IOOIIIOIIIOOOOOOIOOIOOOOIOOIOOII
            def IOIOOOIOIIOIIIOIOIOIIIOOIOOIOO():
                pass
            for __ in range(12): continue
            OIOIOIIOOIOIOOOOIOIOOOOIOOIIIOOO = None
            OIOOIOOIOOIOOIOIIIOOIOIIOOOIIOO = IOOIIIOIIIOOOOOOIOOIOOOOIOOIOOII
            def OI(I, O): pass
            def O(I, O): return None
            OOOIOIOIOIIIIOOIOOIOIIOOIOOOOIOI = (OIOIOOOOIIIOOIOIOIIOIOOOIIOIOOII for OIOIOOOOIIIOOIOIOIIOIOOOIIOIOOII in range(2))
            def IOOIIIOOIOIOOIOOIOIOOIIIOOIOOO():
                return
            class OOOIOOIOIOOOOIOOIOOIOIIOOOIIOI:
                IOOIOOIIIOOIOOOIOIIIOIIOIOOIOOI = None
            def IOOIOOOOIOOIIIOOIOOOIOIIOOOIOO(POI, OOI):
                return POI
            IOOIOOIOOIOOOOIOOOIOOOOIIIOOIO()
            IOIIIIOOIOOIIIIOIIIOIOIOOOIIOOI()
            IOIIOIOOIOIOOIOOOOOOIIIOOIIIOO()
            IOIIOOIOIOIOIOIIOIIIOOOOIIIOOI()
            IOIOOOOIOOIOIIOOIOOIOOIOOIIIOO()
        _6_DUDEPERFECT_ = lambda: None; _7_5MINUTE_CRAFTS_ = lambda: None; _8_DHAR_MANN_ = lambda: None; _9_LOGANPAULVLOGS_ = lambda: None; _10_JEFFREESTAR_ = lambda: None; _11_PEWDIEPIE_ = lambda: None; _12_SNIPERWOLF_ = lambda: None; _13_JAMESCHARLES_ = lambda: None; _14_NINJA_ = lambda: None; _15_JELLY_ = lambda: None; _16_MARKIPLIER_ = lambda: None; _17_PRESTONPLAYZ_ = lambda: None; _18_TROOMTROOM_ = lambda: None; _19_TGFbro_ = lambda: None; _20_UNSPEAKABLE_ = lambda: None
    OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._1_MRBEAST_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._2_COCOMELON_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._3_KIDSDIANA_SHOW_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._4_LIKE_NASTYA_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._5_VLADANDNIKI_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._6_DUDEPERFECT_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._7_5MINUTE_CRAFTS_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._8_DHAR_MANN_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._9_LOGANPAULVLOGS_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._10_JEFFREESTAR_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._11_PEWDIEPIE_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._12_SNIPERWOLF_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._13_JAMESCHARLES_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._14_NINJA_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._15_JELLY_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._16_MARKIPLIER_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._17_PRESTONPLAYZ_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._18_TROOMTROOM_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._19_TGFbro_();OIIIOIOOIOIOOOIOOOOIOIIOIIOIIIO._20_UNSPEAKABLE_()
except Exception:
    pass